/*
 *  OAuthConsumerCredentials.h
 *
 *  Created by Jaanus Kase on 16.01.10.
 *  Copyright 2010. All rights reserved.
 *
 */

#define OAUTH_TWITTER_CONSUMER_KEY @"3SmTphMaKNablHMfnMj3mQ"
#define OAUTH_TWITTER_CONSUMER_SECRET @"SJ9pxd5LV0offDxGgbscWZWe7EihPbvj6SVLaXUNE8"
#define TWITPIC_API_KEY @"309b1edb150b11e48c0e2c1a526f7ae1"

#define OAUTH_FOURSQUARE_CONSUMER_KEY @"PUEV5YPUUBW11RSR1CMKLLYZT5TMXZRL0AC2W1P3WA2RJPJS"
#define OAUTH_FOURSQUARE_CONSUMER_SECRET @"3CWKTTMFNWD3W0KJRLTEWHXFN2IMSX5YIC0D040CNJMZ1WVQ"

#define OAUTH_FOURSQUARE_REDIRECT_URI @"fsqdemo://foursquare"

#define NOTIFY_OAUTH_VERIFY_RECEIVED @"NOTIFY_OAUTH_VERIFY_RECEIVED"
#define OAUTH_CALLBACK_URL @"plainoauth://handleOAuthLogin"

